application:
  profiles:
    - dev
    - test
    - prod
    - 1
    - 2
  props:
      -
        name: YamlList
        url: http://yamllist.dev
        description: Mapping list in Yaml to list of objects in Spring Boot
      -
        ip: 10.10.10.10
        port: 8091
      -
        email: support@yamllist.dev
        contact: http://yamllist.dev/contact
  users:
    -
      username: admin
      password: admin@10@
      roles:
        - READ
        - WRITE
        - VIEW
        - DELETE
    -
      username: guest
      password: guest@01
      roles:
        - VIEW
